language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-tfc' ]; then cd .. && eval "mv $currentfolder generator-tfc" && cd generator-tfc; fi
